INSERT INTO CONTACT (FIRST_NAME,LAST_NAME,BIRTH_DATE) VALUES
('Chris','Shaefer',TO_DATE('1989-12-09','YYYY-MM-DD'));
INSERT INTO CONTACT (FIRST_NAME,LAST_NAME,BIRTH_DATE) VALUES
('Roman','Kushmyruk',TO_DATE('1994-10-23','YYYY-MM-DD'));
INSERT INTO CONTACT (FIRST_NAME,LAST_NAME,BIRTH_DATE) VALUES
('John','Smith',TO_DATE('1964-02-28','YYYY-MM-DD'));
