DROP TABLE CONTACT CASCADE CONSTRAINTS;
DROP TABLE CONTACT_TEL_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE "CONTACT" (
  "ID" NUMBER(5,0) NOT NULL,
  "FIRST_NAME" VARCHAR2(60 BYTE) NOT NULL,
  "LAST_NAME" VARCHAR2 (40 BYTE) NOT NULL,
  "BIRTH_DATE" DATE,
  CONSTRAINT "CONTACT_PK" PRIMARY KEY("ID"),
  CONSTRAINT "UQ_CONTACT_1" UNIQUE ("FIRST_NAME", "LAST_NAME"));

CREATE TABLE "CONTACT_TEL_DETAIL" (
  "ID" NUMBER(5,0) NOT NULL,
  "CONTACT_ID" NUMBER(5,0) NOT NULL,
  "TEL_TYPE" VARCHAR2(20 BYTE) NOT NULL,
  "TEL_NUMBER" VARCHAR2(20 BYTE) NOT NULL,
  CONSTRAINT "UQ_CONTACT_TEL_DETAIL_1"  UNIQUE("CONTACT_ID","TEL_TYPE"),
  CONSTRAINT "CONTACT_TEL_DETAIL_PK" PRIMARY KEY("ID"),
  CONSTRAINT FK_CONTACT_TEL_DETAIL_CONTACT FOREIGN KEY ("CONTACT_ID")
  REFERENCES CONTACT ("ID")
);

CREATE SEQUENCE  "CONTACT_ID"
MINVALUE 1 MAXVALUE 9999
INCREMENT BY 1
START WITH 1
CACHE 20
NOORDER  NOCYCLE ;

CREATE SEQUENCE  "CONTACT_TEL_DETAIL_ID"
MINVALUE 1 MAXVALUE 9999
INCREMENT BY 1
START WITH 1
CACHE 20
NOORDER  NOCYCLE ;

CREATE OR REPLACE TRIGGER CONTACT_ID
BEFORE INSERT ON CONTACT
FOR EACH ROW   BEGIN
  IF :NEW.id IS NULL
  THEN
    SELECT contact_id.nextval INTO :NEW.id FROM dual;
  END IF;
END;

CREATE OR REPLACE TRIGGER CONTACT_TEL_DETAIL_ID
BEFORE INSERT ON CONTACT_TEL_DETAIL
FOR EACH ROW   BEGIN
  IF :NEW.id IS NULL
  THEN
    SELECT CONTACT_TEL_DETAIL_ID.nextval INTO :NEW.id FROM dual;
  END IF;
END;